### PR TITLE
Updated to use Ransack 4.0 and Chronic 0.10.2

### PR DESCRIPTION
**Pull request by raefa**
I was getting security warnings with my use of Ransack 2.4.1. It was telling me to upgrade to Ransack 4.0.0. I found that Ransack 4.0.0 would not work with ransack_chronic so I updated it. I figured I might as well update Chronic while at it.

### CODE REVIEW

**Comment by steveyken** [comment]
@ndbroadbent any chance of merging this? PR looks good to me. We're updating ransack_ui to use ransack v4 so this would be very handy too. Thanks!

**Comment by ndbroadbent** [comment]
Hey @steveyken, sorry for the delay! I'd be happy to add you as an owner here, or move the repo to a different org. Which org would be good?

**Comment by steveyken** [comment]
hey! sure, happy to be added as owner. i doubt it needs to change very much, just keep up with dependencies

**Comment by steveyken** [comment]
thanks for merging

**Comment by CloCkWeRX** [comment]
Could we cut a release for this/publish to rubygems.org? 
(Or if happy, shift to the fat free crm repo which should have a few more owners who can push)

**Comment by steveyken** [comment]
Hey @ndbroadbent I know it was a while back that you indicated you were open to moving this repo. If that's still the case, it could transfer to fatfreecrm org and then @CloCkWeRX would be able to cut gems etc. does that also give permission to release gems?

**Comment by ndbroadbent** [comment]
@steveyken sure I have just moved it to https://github.com/fatfreecrm/ransack_chronic

**Comment by ndbroadbent** [comment]
I just added `steveyken` as a gem maintainer too, but could not add `CloCkWeRX` since that user does not exist on rubygems yet

**Comment by steveyken** [comment]
Thank you! Does 'clockwerx' - all lowercase work? https://rubygems.org/profiles/clockwerx

**Comment by CloCkWeRX** [comment]
Ah thanks!

**Comment by ndbroadbent** [comment]
ah yes clockwerx worked! I've just sent the invite

**Comment by CloCkWeRX** [comment]
So close yet so far - @steveyken , would you mind adding me to the migrated repo; so I can push tags?

(Published https://rubygems.org/gems/ransack_chronic/versions/1.2.0 ; but can't tag here)

**Comment by steveyken** [comment]
Done. Apologies for the delay and missing this

**Pull request merged**
